"""big changes

Revision ID: 297dafe35a64
Revises: 9c78f2720e27
Create Date: 2026-01-19 22:17:06.603166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '297dafe35a64'
down_revision: Union[str, Sequence[str], None] = '9c78f2720e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_match_scores',
                    sa.Column('source_user_id', sa.Integer(), nullable=False),
                    sa.Column('target_user_id', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Float(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('logic_version', sa.String(), nullable=False),
                    sa.Column('breakdown', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['source_user_id'], ['member.id'], ),
                    sa.ForeignKeyConstraint(
                        ['target_user_id'], ['member.id'], ),
                    sa.PrimaryKeyConstraint('source_user_id', 'target_user_id')
                    )
    op.drop_table('sending_history')
    op.drop_table('member_tmp')
    op.drop_table('sudden_change_time_history')
    op.drop_table('change_time_history')
    op.drop_table('matching_state_history')
    op.drop_table('events')
    op.alter_column('date_proposal', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('line_info', 'phone_number',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    nullable=False)
    op.alter_column('line_info', 'user_id',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=False)
    op.alter_column('matching', 'subject_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('matching', 'object_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('matching', 'status',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('matching', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('matching', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=True)
    op.alter_column('matching', 'grading_metric',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('matching', 'obj_grading_metric',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(
        op.f('matching_subject_id_object_id_key'), 'matching', type_='unique')
    op.create_foreign_key(None, 'matching', 'member', ['object_id'], ['id'])
    op.create_foreign_key(None, 'matching', 'member', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'matching', 'member', ['cancel_by_id'], ['id'])
    op.create_foreign_key('fk_matching_last_message', 'matching', 'message', [
                          'last_message_id'], ['id'], use_alter=True)
    op.drop_column('matching', 'selected_place')
    op.drop_column('matching', 'book_phone')
    op.drop_column('matching', 'book_time')
    op.drop_column('matching', 'date2')
    op.drop_column('matching', 'access_token')
    op.drop_column('matching', 'book_name')
    op.drop_column('matching', 'last_sent_at')
    op.drop_column('matching', 'comment')
    op.drop_column('matching', 'place2_name')
    op.drop_column('matching', 'last_change_state_at')
    op.drop_column('matching', 'place2_id')
    op.drop_column('matching', 'place1_id')
    op.drop_column('matching', 'subject_accepted')
    op.drop_column('matching', 'city')
    op.drop_column('matching', 'selected_date')
    op.drop_column('matching', 'current_state')
    op.drop_column('matching', 'place1_url')
    op.drop_column('matching', 'place2_url')
    op.drop_column('matching', 'object_accepted')
    op.drop_column('matching', 'place1_name')
    op.drop_column('matching', 'pause')
    op.drop_column('matching', 'date1')
    op.drop_column('matching', 'date3')
    op.drop_column('matching', 'created_mode')
    op.add_column('member', sa.Column('rank', sa.String(), nullable=True))
    op.add_column('member', sa.Column(
        'marital_status', sa.String(), nullable=True))
    op.add_column('member', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('member', sa.Column(
        'pref_min_height', sa.Integer(), nullable=True))
    op.add_column('member', sa.Column(
        'pref_max_height', sa.Integer(), nullable=True))
    op.add_column('member', sa.Column(
        'pref_oldest_birth_year', sa.Integer(), nullable=True))
    op.add_column('member', sa.Column(
        'pref_youngest_birth_year', sa.Integer(), nullable=True))
    op.alter_column('member', 'name',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=False)
    op.alter_column('member', 'gender',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    nullable=False)
    op.alter_column('member', 'phone_number',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=False)
    op.alter_column('member', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text('true'))
    op.alter_column('member', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('member', 'is_test',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text('false'))
    op.alter_column('member', 'email',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('member', 'id_card_no',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('member', 'fill_form_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    nullable=False)
    op.drop_constraint(op.f('member_phone_number_key'),
                       'member', type_='unique')
    op.create_index(op.f('ix_member_phone_number'),
                    'member', ['phone_number'], unique=True)
    op.alter_column('message', 'content',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=False)
    op.alter_column('message', 'timestamp',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'timestamp',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('message', 'content',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.drop_index(op.f('ix_member_phone_number'), table_name='member')
    op.create_unique_constraint(op.f('member_phone_number_key'), 'member', [
                                'phone_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('member', 'fill_form_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.alter_column('member', 'id_card_no',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('member', 'email',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('member', 'is_test',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text('false'))
    op.alter_column('member', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('member', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text('true'))
    op.alter_column('member', 'phone_number',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('member', 'gender',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    nullable=True)
    op.alter_column('member', 'name',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.drop_column('member', 'pref_youngest_birth_year')
    op.drop_column('member', 'pref_oldest_birth_year')
    op.drop_column('member', 'pref_max_height')
    op.drop_column('member', 'pref_min_height')
    op.drop_column('member', 'height')
    op.drop_column('member', 'marital_status')
    op.drop_column('member', 'rank')
    op.add_column('matching', sa.Column('created_mode',
                  sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'date3', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'date1', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'pause', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'place1_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column('object_accepted',
                  sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'place2_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'place1_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column('current_state',
                  sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column('selected_date',
                  sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column('subject_accepted',
                  sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'place1_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'place2_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column('last_change_state_at', postgresql.TIMESTAMP(
        timezone=True), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'place2_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column('last_sent_at', postgresql.TIMESTAMP(
        timezone=True), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'book_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column('access_token',
                  sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'date2', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'book_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column(
        'book_phone', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matching', sa.Column('selected_place',
                  sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_matching_last_message',
                       'matching', type_='foreignkey')
    op.drop_constraint(None, 'matching', type_='foreignkey')
    op.drop_constraint(None, 'matching', type_='foreignkey')
    op.drop_constraint(None, 'matching', type_='foreignkey')
    op.create_unique_constraint(op.f('matching_subject_id_object_id_key'), 'matching', [
                                'subject_id', 'object_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('matching', 'obj_grading_metric',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('matching', 'grading_metric',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('matching', 'updated_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=True)
    op.alter_column('matching', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('matching', 'status',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('matching', 'object_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('matching', 'subject_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('line_info', 'user_id',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('line_info', 'phone_number',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    nullable=True)
    op.alter_column('date_proposal', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.create_table('events',
                    sa.Column('event', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=True)
                    )
    op.create_table('matching_state_history',
                    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1,
                              maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
                    sa.Column('matching_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('old_state', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('new_state', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'matching_state_history_pkey'))
                    )
    op.create_table('change_time_history',
                    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1,
                              maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
                    sa.Column('member_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('matching_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('change_time_message', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('change_time_history_pkey'))
                    )
    op.create_table('sudden_change_time_history',
                    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1,
                              maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
                    sa.Column('member_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('matching_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('change_time_message', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'sudden_change_time_history_pkey'))
                    )
    op.create_table('member_tmp',
                    sa.Column('name', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('gender', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('phone_number', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('email', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('id_card_no', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('fill_form_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('user_info', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('is_test', sa.BOOLEAN(),
                              autoincrement=False, nullable=True)
                    )
    op.create_table('sending_history',
                    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1,
                              maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
                    sa.Column('matching_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('body', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('send_at', postgresql.TIMESTAMP(timezone=True),
                              autoincrement=False, nullable=True),
                    sa.Column('send_to', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('sending_history_pkey'))
                    )
    op.drop_table('user_match_scores')
    # ### end Alembic commands ###
