"""proposal notification

Revision ID: 8cc6b7053362
Revises: b8bcb33d718d
Create Date: 2026-02-04 20:18:43.194768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc6b7053362'
down_revision: Union[str, Sequence[str], None] = 'b8bcb33d718d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date_proposal', sa.Column('is_pending_notified', sa.Boolean(), nullable=True))
    op.add_column('date_proposal', sa.Column('is_confirmed_notified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('date_proposal', 'is_confirmed_notified')
    op.drop_column('date_proposal', 'is_pending_notified')
    # ### end Alembic commands ###
