"""remove logic

Revision ID: a1a33852e8c9
Revises: 297dafe35a64
Create Date: 2026-01-20 19:26:57.350690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a33852e8c9'
down_revision: Union[str, Sequence[str], None] = '297dafe35a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_match_scores', 'logic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_match_scores', sa.Column('logic_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
