"""add_read_at

Revision ID: b8bcb33d718d
Revises: a1a33852e8c9
Create Date: 2026-02-01 23:38:28.196308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bcb33d718d'
down_revision: Union[str, Sequence[str], None] = 'a1a33852e8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('last_notification_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('message', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'read_at')
    op.drop_column('member', 'last_notification_sent_at')
    # ### end Alembic commands ###
