"""add places and some other column

Revision ID: e63c9c0561c7
Revises: 755bd26686c2
Create Date: 2026-01-11 15:35:46.410337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Boolean, Column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e63c9c0561c7'
down_revision: Union[str, Sequence[str], None] = '755bd26686c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching', Column('place1_name', String()))
    op.add_column('matching', Column('place1_id', String()))
    op.add_column('matching', Column('place2_name', String()))
    op.add_column('matching', Column('place2_id', String()))
    op.add_column('matching', Column('pause', Boolean()))


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_column('matching', 'pause')
    op.drop_column('matching', 'place2_id')
    op.drop_column('matching', 'place2_name')
    op.drop_column('matching', 'place1_id')
    op.drop_column('matching', 'place1_name')
