"""add lead_submission table

Revision ID: 2a5ee9eb0f1c
Revises: f7857eee720f
Create Date: 2026-06-30 20:23:37.649338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a5ee9eb0f1c'
down_revision: Union[str, Sequence[str], None] = 'f7857eee720f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_lead_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leadsubmissionstatus', native_enum=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('converted_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converted_member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_submission_meta_lead_id'), 'lead_submission', ['meta_lead_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_submission_meta_lead_id'), table_name='lead_submission')
    op.drop_table('lead_submission')
    # ### end Alembic commands ###
