"""add notification delivery table

Revision ID: 4ed3c315719f
Revises: c3c600e40eb6
Create Date: 2026-07-31 00:54:54.183955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed3c315719f'
down_revision: Union[str, Sequence[str], None] = 'c3c600e40eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'event_type', 'event_id', name='uq_notification_delivery')
    )
    op.create_index(
        'ix_notification_delivery_event', 'notification_delivery',
        ['event_type', 'event_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_delivery_event', table_name='notification_delivery')
    op.drop_table('notification_delivery')
    # ### end Alembic commands ###
