"""add profile token to member

Revision ID: 8ae98f865561
Revises: d4e8f1a2b3c5
Create Date: 2026-05-26 15:39:20.288770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8ae98f865561'
down_revision: Union[str, Sequence[str], None] = 'd4e8f1a2b3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('profile_token', sa.String(), nullable=True))
    op.add_column('member', sa.Column('profile_token_expires_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'member', ['profile_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='unique')
    op.drop_column('member', 'profile_token_expires_at')
    op.drop_column('member', 'profile_token')
    # ### end Alembic commands ###
