"""add group matching tables

Revision ID: 996f6289572c
Revises: a3bb084266fe
Create Date: 2026-05-26 16:41:42.007299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '996f6289572c'
down_revision: Union[str, Sequence[str], None] = 'a3bb084266fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_matching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cool_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='groupmatchingstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_message_id'], ['group_message.id'], name='fk_group_matching_last_message', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_date_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(), nullable=False),
    sa.Column('proposed_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_matching.id'], ),
    sa.ForeignKeyConstraint(['proposer_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_matching.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'member_id')
    )
    op.create_table('group_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('is_system_notification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_matching.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_message')
    op.drop_table('group_members')
    op.drop_table('group_date_proposal')
    op.drop_table('group_matching')
    # ### end Alembic commands ###
