"""add invite table, remove profile token from member

Revision ID: a3bb084266fe
Revises: 8ae98f865561
Create Date: 2026-05-26 15:46:10.185335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3bb084266fe'
down_revision: Union[str, Sequence[str], None] = '8ae98f865561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.drop_constraint(op.f('member_profile_token_key'), 'member', type_='unique')
    op.drop_column('member', 'profile_token')
    op.drop_column('member', 'profile_token_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('profile_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('member', sa.Column('profile_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('member_profile_token_key'), 'member', ['profile_token'], postgresql_nulls_not_distinct=False)
    op.drop_table('invite')
    # ### end Alembic commands ###
