"""add is_match_notified to matching

Revision ID: a96abb7bc589
Revises: c3a1d9e0f2b4
Create Date: 2026-03-17 00:05:21.323296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a96abb7bc589'
down_revision: Union[str, Sequence[str], None] = 'c3a1d9e0f2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DROP TABLE IF EXISTS member_tmp")
    op.execute("ALTER TABLE matching ADD COLUMN IF NOT EXISTS is_match_notified BOOLEAN")
    op.execute("UPDATE matching SET is_match_notified = TRUE WHERE is_match_notified IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matching', 'obj_grading_metric',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matching', 'grading_metric',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matching', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('matching', 'is_match_notified')
    op.create_table('member_tmp',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_card_no', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fill_form_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_test', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
