"""add last_seen_at to member

Revision ID: d9a086aab71d
Revises: a96abb7bc589
Create Date: 2026-03-17 00:15:27.149139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a086aab71d'
down_revision: Union[str, Sequence[str], None] = 'a96abb7bc589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'last_seen_at')
    # ### end Alembic commands ###
