"""add join_campaign to member

Revision ID: f7857eee720f
Revises: fa248fed06b4
Create Date: 2026-06-24 15:13:32.758631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7857eee720f'
down_revision: Union[str, Sequence[str], None] = 'fa248fed06b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('join_campaign', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'join_campaign')
    # ### end Alembic commands ###
