"""add_pref_locks_to_member

Revision ID: fa248fed06b4
Revises: a1b2c3d4e5f6
Create Date: 2026-06-22 10:57:19.640043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa248fed06b4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_tmp')
    op.create_foreign_key('fk_group_matching_last_message', 'group_matching', 'group_message', ['last_message_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('group_membership_group_id_member_id_key'), 'group_membership', type_='unique')
    op.add_column('member', sa.Column('pref_locks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'pref_locks')
    op.create_unique_constraint(op.f('group_membership_group_id_member_id_key'), 'group_membership', ['group_id', 'member_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('fk_group_matching_last_message', 'group_matching', type_='foreignkey')
    op.create_table('member_tmp',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_card_no', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fill_form_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_test', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
