[project]
name = "senders"
version = "1.0"
description = "Related to line sending"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "line-bot-sdk>=3.17.1",
    "psycopg[binary]>=3.2.9",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
]

